config {
  type: "view",
  name: "CITA_Edge_Golden"
}

SELECT
  e.id_evento AS source_id,
  c.confrontado_com_id AS target_id,
  CASE
    WHEN c.status_entrega = 'Entregue' THEN 'VALID'
    ELSE 'PENDING'
  END AS validation_status
FROM
  ${ref("vibe-cabral.revelia_landing_zone.eventos_unstructured")} e
JOIN
  ${ref("vibe-cabral.revelia_landing_zone.citacoes_raw")} c
ON
  e.proc_ref = c.num_proc
WHERE
  UPPER(e.txt_movimento) LIKE '%CITACAO%'
